### ISSUE TITLE
Strategic plan

### ISSUE THREAD

**Issue by Karvovskaya** [Karvovskaya/RDM_Community#2]
- [ ] A strategic plan is broken into objectives that we seek to achieve before a given milestone. This
milestone can be measured in either time or a specific achievement. 

- [ ] Regular milestone achievements give your
community a much-needed dose of excitement and satisfaction.

- [ ] You should remember to fulfill your role as a
facilitator and work with your community in a transparent fashion to combine input, feedback,
and opinion into a single consistent plan that everyone can follow.

* *The success criteria* describe a set of measurable methods for evaluating the goal’s success.
You should be able to look at this statement and determine straightaway whether the goal
was achieved (example: 20 new community members).
* *The implementation plan* describes what tasks need to happen to achieve the goal. These
are a set of directions that clearly indicate the steps involved in achieving the goal.
*  Specify *the owner*: the person responsible for the goal. Accountability is an important element in building successful community: when people feel responsible for their work, they ensure that positive outcomes are generated.

## SUCCESS CRITERIA: 
Item
Item
## IMPLEMENTATION PLAN:
Item
Item
## SUCCESS CRITERIA:
Item
Item
## IMPLEMENTATION PLAN:
Item
Item
## OWNER:
